version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PG_HOST: db
      PG_LOGIN: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DB: ${POSTGRES_DB}
      HIKARI_BOT_TOKEN: ${HIKARI_BOT_TOKEN} 
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data